//
//  SynchronizationInteractor.swift
//  NotesApp
//
//  Created by Сашок on 13.05.2022.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol SynchronizationBusinessLogic {
    func toggleSynchronization()
    func updateSynchronizationStatus()
}

class SynchronizationInteractor: SynchronizationBusinessLogic {
    var presenter: SynchronizationPresentationLogic?
    var worker = SynchronizationWorker()
    
    func toggleSynchronization() {
        if worker.isSynchronizationEnabled() {
            worker.disableSynchronization()
            updateSynchronizationStatus()
        } else {
            worker.enableSynchronization(completion: updateSynchronizationStatus)
        }
    }
    
    func updateSynchronizationStatus() {
        let synchronizationEnabled = worker.isSynchronizationEnabled()
        let response = Synchronization.UpdateStatus.Response(synchronizationEnabled: synchronizationEnabled)
        
        presenter?.presentSynchronizationStatus(response: response)
    }
}
