//
//  SynchronizationModels.swift
//  NotesApp
//
//  Created by Сашок on 13.05.2022.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum Synchronization {
    enum UpdateStatus {
        struct Response {
            let synchronizationEnabled: Bool
        }
        
        struct ViewModel {
            let statusText: String
            let systemImageName: String
            let actionsText: String
            let buttonText: String
        }
    }
}
