//
//  NoteDetailsModels.swift
//  NotesApp
//
//  Created by Сашок on 13.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum NoteDetails {
    enum ShowNote {
        struct Response {
            let title: String?
            let content: String?
            let color: Int64?
        }
        
        struct ViewModel {
            let title: String
            let content: String
            let color: Int64
            let navigationTitle: String
        }
    }
    
    enum SetNoteColor {
        struct Request {
            let color: Int64
        }
        
        struct Response {
            let color: Int64
        }
        
        struct ViewModel {
            let color: Int64
        }
    }
    
    enum SetNoteTitle {
        struct Request {
            let title: String?
        }
    }
    
    enum SetNoteContent {
        struct Request {
            let content: String?
        }
    }
}
