//
//  NoteDetailsRouter.swift
//  NotesApp
//
//  Created by Сашок on 13.05.2022.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NoteDetailsRoutingLogic {
    func routeToColorPicker(with selectedColor: UIColor?)
}

protocol NoteDetailsDataPassing {
    var dataStore: NoteDetailsDataStore? { get }
}

class NoteDetailsRouter: NSObject, NoteDetailsRoutingLogic, NoteDetailsDataPassing {
    weak var viewController: NoteDetailsViewController?
    var dataStore: NoteDetailsDataStore?
    
    func routeToColorPicker(with selectedColor: UIColor?) {
        let colorPickerController = UIColorPickerViewController()
        if let selectedColor = selectedColor {
            colorPickerController.selectedColor = selectedColor
        }
        colorPickerController.delegate = viewController
        viewController?.present(colorPickerController, animated: true)
    }
}
