//
//  NoteDetailsInteractor.swift
//  NotesApp
//
//  Created by Сашок on 13.05.2022.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol NoteDetailsBusinessLogic {
    func provideNote()
    func saveNote()
    func updateNoteColor(request: NoteDetails.SetNoteColor.Request)
    func updateNoteTitle(request: NoteDetails.SetNoteTitle.Request)
    func updatenoteContent(request: NoteDetails.SetNoteContent.Request)
}

protocol NoteDetailsDataStore {
    var note: NoteMO? { get set }
}

class NoteDetailsInteractor: NoteDetailsBusinessLogic, NoteDetailsDataStore {
    var worker: NoteDetailsWorker = NoteDetailsWorker()
    
    var presenter: NoteDetailsPresentationLogic?
    var note: NoteMO?

    func provideNote() {
        let response = NoteDetails.ShowNote.Response(note: note)
        presenter?.presentNote(response: response)
    }
    
    func saveNote() {
        worker.saveNote(note: note)
    }
    
    func updateNoteColor(request: NoteDetails.SetNoteColor.Request) {
        note?.color = request.color
        
        let response = NoteDetails.SetNoteColor.Response(color: request.color)
        presenter?.presentNoteColor(response: response)
    }
    
    func updateNoteTitle(request: NoteDetails.SetNoteTitle.Request) {
        note?.title = request.title
    }
    
    func updatenoteContent(request: NoteDetails.SetNoteContent.Request) {
        note?.content = request.content
    }
}
