//
//  NoteDetailsInteractor.swift
//  NotesApp
//
//  Created by Сашок on 13.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol NoteDetailsBusinessLogic {
    func provideNote()
    
    func saveNote(request: NoteDetails.SaveNote.Request)
    
    func updateNoteColor(request: NoteDetails.SetNoteColor.Request)
    
    func updateNoteTitle()
    func updatenoteContent()
}

protocol NoteDetailsDataStore: AnyObject {
    var note: NoteMO? { get set }
}

class NoteDetailsInteractor: NoteDetailsBusinessLogic, NoteDetailsDataStore {
    
    var presenter: NoteDetailsPresentationLogic?
    var worker: NoteDetailsWorker?
    var note: NoteMO?

    func provideNote() {
        let response = NoteDetails.ShowNote.Response(
            title: note?.title,
            content: note?.content,
            color: note?.color
        )
        
        presenter?.presentNote(response: response)
    }
    
    func saveNote(request: NoteDetails.SaveNote.Request) {
        note?.title = request.title
        note?.content = request.content

        worker = NoteDetailsWorker()
        worker?.saveNote(note: note)
    }
    
    func updateNoteColor(request: NoteDetails.SetNoteColor.Request) {
        note?.color = request.color ?? 4294901811
        
        let response = NoteDetails.SetNoteColor.Response(color: request.color ?? 4294901811)
        presenter?.presentNoteColor(response: response)
    }
    
    func updateNoteTitle() {
        
    }
    
    func updatenoteContent() {
        
    }
}
