//
//  NoteDetailsPresenter.swift
//  NotesApp
//
//  Created by Сашок on 13.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol NoteDetailsPresentationLogic {
    func presentNote(response: NoteDetails.ShowNote.Response)
    
    func presentNoteColor(response: NoteDetails.SetNoteColor.Response)
}

class NoteDetailsPresenter: NoteDetailsPresentationLogic {
    
    weak var viewController: NoteDetailsDisplayLogic?
    
    func presentNote(response: NoteDetails.ShowNote.Response) {
        
        let viewModel = NoteDetails.ShowNote.ViewModel(
            title: response.title ?? "",
            content: response.content ?? "",
            color: response.color ?? 4294901811
        )
        
        viewController?.displayNote(viewModel: viewModel)
    }
    
    func presentNoteColor(response: NoteDetails.SetNoteColor.Response) {
        let viewModel = NoteDetails.SetNoteColor.ViewModel(color: response.color)
        
        viewController?.updateNoteColor(viewModel: viewModel)
    }
}
