//
//  NoteDetailsRouter.swift
//  NotesApp
//
//  Created by Сашок on 13.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NoteDetailsRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol NoteDetailsDataPassing {
    var dataStore: NoteDetailsDataStore? { get }
}

class NoteDetailsRouter: NSObject, NoteDetailsRoutingLogic, NoteDetailsDataPassing {
    
    weak var viewController: NoteDetailsViewController?
    var dataStore: NoteDetailsDataStore?
    
    // MARK: Routing
    /*
    func routeToSomewhere(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! SomewhereViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }
    */
    
    // MARK: Navigation
    /*
    func navigateToSomewhere(source: NoteDetailsViewController, destination: SomewhereViewController) {
        source.show(destination, sender: nil)
    }
    */
    
    // MARK: Passing data
    /*
    func passDataToSomewhere(source: NoteDetailsDataStore, destination: inout SomewhereDataStore) {
        destination.name = source.name
    }
    */
}
