//
//  NoteDetailsWorker.swift
//  NotesApp
//
//  Created by Сашок on 13.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class NoteDetailsWorker {
    func saveNote(note: NoteMO?) {
        guard let note = note else {
            return
        }
        
        let noteIsEmpty = (note.title?.isEmpty ?? true) && (note.content?.isEmpty ?? true)
        
        if noteIsEmpty {
            YandexDiskSynchronizatinManager.shared.deleteNote(note)
            StorageService.shared.delete(note: note)
        } else {
            YandexDiskSynchronizatinManager.shared.uploadNote(note)
            StorageService.shared.save(note: note)
        }
        
        
    }
}
