//
//  NoteTableModels.swift
//  NotesApp
//
//  Created by Сашок on 14.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum NoteTable {

    // MARK: Use cases
    enum Something {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum AddNote {
        struct Response {
            let newNoteIndexPath: IndexPath?
        }
        
        struct ViewModel {
            let newNoteIndexPath: IndexPath?
        }
    }
    
    enum DeleteNote {
        struct Request {
            let indexPath: IndexPath
        }
    }
    
    enum PinNote {
        struct Request {
            let indexPath: IndexPath
        }
        
    }
    
    enum FiletrNotes {
        struct Request {
            let searchText: String
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    struct CellViewModel {
        let title: String
        let content: String
        let color: Int64
        let pinned: Bool
    }
}
