//
//  NoteTablePresenter.swift
//  NotesApp
//
//  Created by Сашок on 14.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol NoteTablePresentationLogic {

    func presentNewNote(response: NoteTable.AddNote.Response)
    
    
    func beginUpdates()
    func endUpdates()
    func insertRow(at indexPath: IndexPath)
    func updateRow(at indexPath: IndexPath)
    func deleteRow(at indexPath: IndexPath)
    func moveRow(from oldIndexPath: IndexPath, to newIndexPath: IndexPath)
    
    func reloadTable()
    
    func endRefreshing()
}

class NoteTablePresenter: NoteTablePresentationLogic {
    
    weak var viewController: NoteTableDisplayLogic?
    
    
    func presentNewNote(response: NoteTable.AddNote.Response) {
        let viewModel = NoteTable.AddNote.ViewModel(newNoteIndexPath: response.newNoteIndexPath)
        viewController?.displayNewNote(viewModel: viewModel)
    }
    
    func beginUpdates() {
        viewController?.beginTableUpdates()
    }
    
    func endUpdates() {
        viewController?.endTableUpdates()
    }
    
    func insertRow(at indexPath: IndexPath) {
        viewController?.insertRow(at: indexPath)
    }
    
    func updateRow(at indexPath: IndexPath) {
        viewController?.updateRow(at: indexPath)
    }
    
    func deleteRow(at indexPath: IndexPath) {
        viewController?.deleteRow(at: indexPath)
    }
    
    func moveRow(from oldIndexPath: IndexPath, to newIndexPath: IndexPath) {
        viewController?.moveRow(from: oldIndexPath, to: newIndexPath)
    }
    
    func reloadTable() {
        viewController?.reloadTable()
    }
    
    func endRefreshing() {
        viewController?.endRefreshing1()
    }
}
