//
//  SyncInteractor.swift
//  NotesApp
//
//  Created by Сашок on 13.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol SynchronizationBusinessLogic {
    func enableSynchronization()
    func disableSynchronization()
    func updateSynchronizationStatus()
}

class SynchronizationInteractor: SynchronizationBusinessLogic {
    var presenter: SynchronizationPresentationLogic?
    var worker: SynchronizationWorker?
    
    func enableSynchronization() {
        worker = SynchronizationWorker()
        worker?.enableSynchronization(completion: updateSynchronizationStatus)
    }
    
    func disableSynchronization() {
        worker = SynchronizationWorker()
        worker?.disableSynchronization()
        
        updateSynchronizationStatus()
    }
    
    func updateSynchronizationStatus() {
        worker = SynchronizationWorker()

        let isAuthenticated = worker?.isSynchronizationEnabled() ?? false
        let response = Synchronization.UpdateSynchronizationStatus.Response(synchronizationEnabled: isAuthenticated)
        
        presenter?.presentSynchronizationStatus(response: response)
    }
}
