//
//  SyncViewController.swift
//  NotesApp
//
//  Created by Сашок on 13.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SynchronizationDisplayLogic: AnyObject {
    func displaySynchronizationStatus(viewModel: Synchronization.UpdateStatus.ViewModel)
}

class SynchronizationViewController: UIViewController {
    // MARK: - IBOutlets
    @IBOutlet weak var synchronizationStatusLabel: UILabel!
    @IBOutlet weak var synchronizationStatusImageView: UIImageView!
    @IBOutlet weak var enableSynchronizationElementsStackView: UIStackView!
    @IBOutlet weak var disableSynchronizationElementsStackView: UIStackView!
    
    // MARK: - 
    var interactor: SynchronizationBusinessLogic?
    
    // MARK: - Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        makeAssembly()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        makeAssembly()
    }
    
    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        updateSyncStatus()
    }
}

// MARK: - User actions handling
extension SynchronizationViewController {
    @IBAction func enableSynchronizationButtonTapped(_ sender: UIButton) {
        sender.tapAnimation {
            self.interactor?.enableSynchronization()
        }
    }
    
    @IBAction func disableSynchronizationButtonTapped(_ sender: UIButton) {
        sender.tapAnimation {
            self.interactor?.disableSynchronization()
        }
    }
}

// MARK: - SyncDisplayLogic
extension SynchronizationViewController: SynchronizationDisplayLogic {
    func displaySynchronizationStatus(viewModel: Synchronization.UpdateStatus.ViewModel) {
        updateButtonsVisibility(isAuthenticated: viewModel.synchronizationEnabled)
        
        synchronizationStatusImageView.image = UIImage(systemName: viewModel.imageName)
        synchronizationStatusLabel.text = viewModel.statusText
    }
}

// MARK: - Private methods
extension SynchronizationViewController {
    private func makeAssembly() {
        let viewController = self
        let interactor = SynchronizationInteractor()
        let presenter = SynchronizationPresenter()

        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }
    
    private func updateSyncStatus() {
        interactor?.updateSynchronizationStatus()
    }
    
    private func updateButtonsVisibility(isAuthenticated: Bool) {
        if isAuthenticated {
            enableSynchronizationElementsStackView.isHidden = true
            disableSynchronizationElementsStackView.isHidden = false
        } else {
            enableSynchronizationElementsStackView.isHidden = false
            disableSynchronizationElementsStackView.isHidden = true
        }
    }
}


