//
//  NoteDetailsWorker.swift
//  NotesApp
//
//  Created by Сашок on 13.05.2022.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class NoteDetailsWorker {
    func saveNote(note: NoteMO?) {
        guard let note = note else {
            return
        }
        
        if (note.title?.isEmpty ?? true) && (note.content?.isEmpty ?? true) {
            YandexDiskSynchronizatinManager.shared.deleteNote(note)
            CoreDataService.shared.delete(note: note)
        } else {
            YandexDiskSynchronizatinManager.shared.uploadNote(note)
            CoreDataService.shared.save(note: note)
        }
    }
}
