//
//  SyncPresenter.swift
//  NotesApp
//
//  Created by Сашок on 13.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol SyncPresentationLogic {

    func presentAuthenticationStatus(response: Sync.UpdateAuthenticationStatus.Response)
}

class SyncPresenter: SyncPresentationLogic {
    
    weak var viewController: SyncDisplayLogic?
    
    func presentAuthenticationStatus(response: Sync.UpdateAuthenticationStatus.Response) {
        let viewModel = Sync.UpdateAuthenticationStatus.ViewModel(
            isAuthenticated: response.isAuthenticated,
            imageName: response.isAuthenticated ? "checkmark.icloud" : "xmark.icloud",
            syncStatus: response.isAuthenticated ? "Синхронизация включена" : "Синхронизация выключена"
        )
        
        viewController?.displayAuthenticationStatus(viewModel: viewModel)
    }
}
